---
title: "BiTE Results"
format: html
editor: visual
---

```{r}
load("Bite Rendering.RData")
#Load libraries
source("FAERS_Libs.R")
```

**Characteristics of BiTE-related cases reported in the FAERS Database**

From October 2014 to September 2023, a total of `r analytic_ss` FAERS cases were included in this analysis. Of these, `r bite_ss` cases of BiTE-related AEs were reported. Among BiTE-related AEs, `r drug_props[bli == 1, N] %>% comma` (`r drug_props[bli == 1, prop]`%) and `r drug_props[tec == 1, N] %>% comma` (`r drug_props[tec == 1, prop]` %) listed blinatumomab and teclistamab respectively as the primary suspected drug. Mosunetuzumab (`r drug_props[mos == 1, N] %>% comma` reports; `r drug_props[mos == 1, prop]`%), glofitamab (`r drug_props[glo == 1, N] %>% comma` reports; `r drug_props[glo == 1, prop]`%), and epcoritamab (`r drug_props[epc == 1, N] %>% comma` reports; `r drug_props[epc == 1, prop]`%) accounted for a smaller proportion. The indication for BiTE therapy was leukemia/lymphoma in `r ll_mm_props[ll == 1 & mm == 0, prop]`% of cases, MM in `r ll_mm_props[ll == 0 & mm == 1, prop]`% of cases, and both in `r ll_mm_props[ll == 1 & mm == 1, prop]`% of cases. The median age of patients was `r age_iqr["50%"]` years (IQR: `r (age_iqr["75%"] %>% as.numeric - age_iqr["25%"] %>% as.numeric) %>% format(nsmall = 1)` years) and `r sex_props[sex == "Female", prop]`% of BiTE recipients were female. Most reports came from the US (`r country_props[reporter_country == "US", prop]`%), Japan (`r country_props[reporter_country == "JP", prop]`%), or France (`r country_props[reporter_country == "FR", prop]`%), with the rest of reports (`r 100 - (country_props[reporter_country == "FR", prop] + country_props[reporter_country == "JP", prop] + country_props[reporter_country == "US", prop])`%) coming from `r (country_props$reporter_country %>% length) - 3` different countries. `r occp_props[!occp_cod %in% c("", "CN"), prop] %>% sum`% of the reports were made by health professionals, `r occp_props[occp_cod %in% c("CN"), prop]`% by consumers, and `r occp_props[occp_cod %in% c(""), prop]`% did not state the reporting source.

**Frequency and Associations of CVAEs reported with BiTE**

  From a total of `r bite_ss` cases with a reported BiTE-related AE, `r mres_df[var == "bite" & outcome == "cvae", n_ae]` (`r mres_df[var == "bite" & outcome == "cvae", ae_prop] %>% format(nsmall = 1)`%) involved a CVAE (**Figure 1**). **Figure 2** shows the most frequently reported CVAEs. These were bleeding (`r mres_df[var == "bite" & outcome == "bleed", n_ae]` events), thromboembolic events (`r mres_df[var == "bite" & outcome == "te", n_ae]` events), hypotension (`r mres_df[var == "bite" & outcome == "hypotension", n_ae]` events), shock (`r mres_df[var == "bite" & outcome == "shock", n_ae]` events), and heart failure (`r mres_df[var == "bite" & outcome == "hf", n_ae]` events). Additional CVAEs included atrial fibrillation/flutter (`r mres_df[var == "bite" & outcome == "af", n_ae]` events), pericardial effusions (`r mres_df[var == "bite" & outcome == "peri_eff", n_ae]` events), myocardial infarction (`r mres_df[var == "bite" & outcome == "mi", n_ae]` events), ventricular tachyarrhythmia (`r mres_df[var == "bite" & outcome == "vta", n_ae]` events), myocarditis (`r mres_df[var == "bite" & outcome == "myo", n_ae]` events), pericarditis (`r mres_df[var == "bite" & outcome == "pericarditis", n_ae]` events) , and sudden death (`r mres_df[var == "bite" & outcome == "sd", n_ae]` event) **(Table 1)**.

  Of these, in multivariable logistic regression models, BiTEs as a class were associated with myocarditis `r mres_df[var == "bite" & outcome == "myo", es]`, hypotension (`r mres_df[var == "bite" & outcome == "hypotension", es]`) and DIC (`r mres_df[var == "bite" & outcome == "dic", es]`). Blinatumomab was the primary driver of these associations for both of DIC (`r mres_df[var == "bli" & outcome == "dic", es]`) and hypotension (`r mres_df[var == "bli" & outcome == "hypotension", es]`). In contrast, teclistamab was associated with myocarditis  (`r mres_df[var == "tec" & outcome == "myo", es]`) and shock  (`r mres_df[var == "tec" & outcome == "shock", es]`) **(Table 1)**. No significant associations with CVAE were observed with the other 3 BiTE products (glofitamab, mosunetuzumab, and epcoritamab).

  BiTEs were not associated with overall CVAE (`r mres_df[var == "bite" & outcome == "cvae", es]`) but were significantly associated with fatal CVAE (`r mres_df[var == "bite" & outcome == "dcvae", es]`). There was no statistically significant interaction with age or  sex (*P* for interaction between BiTE and age/sex: `r mres_df[var == "bite" & outcome == "dcvae", sex_int] %>% as.numeric %>% r2` and `r mres_df[var == "bite" & outcome == "dcvae", age_int] %>% as.numeric %>% r2` respecitvely). Individually, the association with fatal CVAEs was most apparent with teclistamab (`r mres_df[var == "tec" & outcome == "dcvae", es]`). Of the `r mres_df[var == "bite" & outcome == "dcvae", n_ae]` fatal BiTE-associated fatal CVAEs, `r mres_df[var == "bite" & outcome == "dcvae", n_ae] - mres_df[var == "bite" & outcome == "dcvae", n_comorbid_cvae]` (`r 100 - mres_df[var == "bite" & outcome == "dcvae", "prop_comorbid_cvae"]`%) occurred in patients without a recorded cardiovascular comorbidity. The proportion of fatal CVAEs was comparable in patients with or without recorded cardiovascular comorbidities (`r dcvae_comorbid_pct`% versus `r dcvae_no_comorbid_pct`%, respectively).

**Time to onset of BiTE-related AEs**

  **Figure 3** shows the time to onset of CVAEs in comparison with non-CVAEs. In general, CVAEs tended to occur sooner following BiTE therapy compared to non-CVAEs (median time-to-onset: `r cvae_mtime` days versus `r ncvae_mtime` days; *P* `r cvae_time_p`).  **Supplementary Figure 1** shows the time to onset of specific CVAEs. DIC and hypotension events occurred at a median time of `r dic_mtime` and `r hypotension_mtime` days following BiTE initation respecitvely, which was slightly earlier compared to other CVAEs (*P* = `r dic_time_p` and `r hypotension_time_p` for DIC and hypotension respectively).

**Mortality rates associated with BiTE-related CVAEs**

  CVAEs were associated with a significantly higher risk of mortality compared with non-CVAEs (`r mres_df[var == "bite" & outcome == "cvae", prop_death] %>% format(nsmall = 1)`% versus `r mres_df[var == "bite" & outcome == "ncvae", prop_death] %>% format(nsmall =1)`%; *P* `r mort_rr_df[drug == "bite" & ae == "cvae", pval] %>% format(nsmall = 1)`) **(Figures 3 and 4)**. The CVAEs with the highest mortality rates were myocarditis (`r mres_df[var == "bite" & outcome == "myo", prop_death]`%), shock (`r mres_df[var == "bite" & outcome == "shock", prop_death]`%), heart failure (`r mres_df[var == "bite" & outcome == "hf", prop_death]`%), DIC (`r mres_df[var == "bite" & outcome == "dic", prop_death]`%), and bleeding (`r mres_df[var == "bite" & outcome == "bleed", prop_death]`%). Conversely, mortality rates associated with CRS (`r mres_df[var == "bite" & outcome == "crs", prop_death]`%), neurotoxicity (`r mres_df[var == "bite" & outcome == "neuro", prop_death]`%), and infections (`r mres_df[var == "bite" & outcome == "infection", prop_death]`%) were lower **(Figure 4)**.

  **Figure 5** shows the corresponding RR (adjusted for age and sex) for mortality with each AE in multivariable regression models adjusted for age and sex. CVAEs as a whole were associated with significantly higher mortality rates compared to non-CVAEs (`r mort_rr_df[drug == "bite" & ae == "cvae", es]`). Specific CVAEs associated with statistically significant increases in mortality included shock (`r mort_rr_df[drug == "bite" & ae == "shock", es]`), HF (`r mort_rr_df[drug == "bite" & ae == "hf", es]`),  bleeding (`r mort_rr_df[drug == "bite" & ae == "bleed", es]`), DIC (`r mort_rr_df[drug == "bite" & ae == "dic", es]`), thromboembolic disease (`r mort_rr_df[drug == "bite" & ae == "te", es]`), and venous thromboembolic disease (`r mort_rr_df[drug == "bite" & ae == "vte", es]`).

  Among non-CVAEs, infections (`r mort_rr_df[drug == "bite" & ae == "infection", es]`) were associated with statistically significant increases in mortality but CRS (`r mort_rr_df[drug == "bite" & ae == "crs", es]`) and neurotoxicity (`r mort_rr_df[drug == "bite" & ae == "neuro", es]`) were not.

**Overlap rates between BiTE-related CVAEs and CRS**

  The 3 CVAEs which most frequently co-occurred with CRS were DIC (`r mres_df[var == "bite" & outcome == "dic", n_crs]` of `r mres_df[var == "bite" & outcome == "dic", n_ae]` events; `r mres_df[var == "bite" & outcome == "dic", prop_crs]`%), myocaridtis (`r mres_df[var == "bite" & outcome == "myo", n_crs]` of `r mres_df[var == "bite" & outcome == "myo", n_ae]` events; `r mres_df[var == "bite" & outcome == "myo", prop_crs]`%), and heart failure (`r mres_df[var == "bite" & outcome == "hf", n_crs]` of `r mres_df[var == "bite" & outcome == "hf", n_ae]` events; `r mres_df[var == "bite" & outcome == "myo", prop_crs]`%).  Overall, the rates of overlap between CVAEs and CRS were low (`r mres_df[var == "bite" & outcome == "cvae", prop_crs]`%), as were the rates of overlap between fatal CVAEs and CRS (`r mres_df[var == "bite" & outcome == "dcvae", prop_crs]`%). Additionally, most cases of neurotoxicity and infection did not occur in the context of CRS **(Figure 6)**.